In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('/content/credit_data.csv')

In [4]:
df

i#clientid        income        age         loan  c#default
0              1  66155.925095  59.017015  8106.532131          0
1              2  34415.153966  48.117153  6564.745018          0
2              3  57317.170063  63.108049  8020.953296          0
3              4  42709.534201  45.751972  6103.642260          0
4              5  66952.688845  18.584336  8770.099235          1
...          ...           ...        ...          ...        ...
1995        1996  59221.044874  48.518179  1926.729397          0
1996        1997  69516.127573  23.162104  3503.176156          0
1997        1998  44311.449262  28.017167  5522.786693          1
1998        1999  43756.056605  63.971796  1622.722598          0
1999        2000  69436.579552  56.152617  7378.833599          0

[2000 rows x 5 columns]

In [5]:
df.count()

i#clientid    2000
income        2000
age           1997
loan          2000
c#default     2000
dtype: int64

In [6]:
df.head(10)

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1
5           6  24904.064140  57.471607    15.498598          0
6           7  48430.359613  26.809132  5722.581981          0
7           8  24500.141984  32.897548  2971.003310          1
8           9  40654.892537  55.496853  4755.825280          0
9          10  25075.872771  39.776378  1409.230371          0

In [7]:
df.isna()

i#clientid  income    age   loan  c#default
0          False   False  False  False      False
1          False   False  False  False      False
2          False   False  False  False      False
3          False   False  False  False      False
4          False   False  False  False      False
...          ...     ...    ...    ...        ...
1995       False   False  False  False      False
1996       False   False  False  False      False
1997       False   False  False  False      False
1998       False   False  False  False      False
1999       False   False  False  False      False

[2000 rows x 5 columns]

In [8]:
df.isnull().sum()

i#clientid    0
income        0
age           3
loan          0
c#default     0
dtype: int64

Upon loading the data we checked for missing values in the data

Column named age has 3 values missing, so we are filling the missing values of age column with mean of the whole age column

In [12]:
df=df.fillna(np.mean(df['age']))

In [13]:
df.isnull().sum()

i#clientid    0
income        0
age           0
loan          0
c#default     0
dtype: int64

  Here, At this point there are no missing values in the dataset

In [14]:
df.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [28]:
output=df[['c#default']]

In [29]:
output

c#default
0             0
1             0
2             0
3             0
4             1
...         ...
1995          0
1996          0
1997          1
1998          0
1999          0

[2000 rows x 1 columns]

In [19]:
input=df[['income','age','loan']]

In [20]:
input

income        age         loan
0     66155.925095  59.017015  8106.532131
1     34415.153966  48.117153  6564.745018
2     57317.170063  63.108049  8020.953296
3     42709.534201  45.751972  6103.642260
4     66952.688845  18.584336  8770.099235
...            ...        ...          ...
1995  59221.044874  48.518179  1926.729397
1996  69516.127573  23.162104  3503.176156
1997  44311.449262  28.017167  5522.786693
1998  43756.056605  63.971796  1622.722598
1999  69436.579552  56.152617  7378.833599

[2000 rows x 3 columns]

In [49]:
input = df.iloc[:, 1:4].values

In [50]:
input

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [51]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

In [52]:
input=scaler.fit_transform(input)

In [53]:
input

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [54]:
input.shape

(2000, 3)

In [55]:
output.shape

(2000, 1)

Now, let's make a neural network to complete the classification

In [56]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(sigmoid):
  return sigmoid*(1-sigmoid)



In [57]:
weights0=2* np.random.random((3,10))-1
weights1=2*np.random.random((10,1))-1

In [79]:
epochs=20000
learning_rate=0.01
error=[]


for epoch in range(epochs):
  input_layer=input
  sum_synapse0=input_layer.dot(weights0)
  hidden_layer=sigmoid(sum_synapse0)

  sum_synapse1=hidden_layer.dot(weights1)
  output_layer=sigmoid(sum_synapse1)

  error_output_layer=output-output_layer
  average_error=np.mean(abs(error_output_layer))

  if(epoch%1000==0):
    print("Epoch: "+str(epoch+1) + "Error: "+ str(average_error))
    error.append(average_error)
  #calculating the delta at the output layer
  delta_output_layer=error_output_layer* sigmoid_derivative(output_layer)

 # calculating delta at hidden_layer
  weights1t=weights1.T
  delta_output_layer_x_hidden_layer=delta_output_layer.dot(weights1t)
  delta_hidden_layer=delta_output_layer_x_hidden_layer*sigmoid_derivative(hidden_layer)

  # updating weights from output layer to the hidden layer
  hidden_layert=hidden_layer.T
  hidden_layer_x_delta_output_layer=hidden_layert.dot(delta_output_layer)

  weights1=weights1+(hidden_layer_x_delta_output_layer * learning_rate)

  #updating weights from the hidden layer to the output layer
  input_layert=input_layer.T
  input_layer_x_delta_hidden_layer=input_layert.dot(delta_hidden_layer)
  weighst0=weights0 + (input_layer_x_delta_hidden_layer *learning_rate)



Epoch: 1Error: 0.09798230780697456
Epoch: 1001Error: 0.09701305185989807
Epoch: 2001Error: 0.09611852706797956
Epoch: 3001Error: 0.09528982070327925
Epoch: 4001Error: 0.0945194376965101
Epoch: 5001Error: 0.09380102329444995
Epoch: 6001Error: 0.0931291492835212
Epoch: 7001Error: 0.09249914724966865
Epoch: 8001Error: 0.09190697711296823
Epoch: 9001Error: 0.09134912244290579
Epoch: 10001Error: 0.09082250633592723
Epoch: 11001Error: 0.09032442324548333
Epoch: 12001Error: 0.08985248330757668
Epoch: 13001Error: 0.08940456654143847
Epoch: 14001Error: 0.08897878491930246
Epoch: 15001Error: 0.0885734507552842
Epoch: 16001Error: 0.08818705020537264
Epoch: 17001Error: 0.08781822092945098
Epoch: 18001Error: 0.0874657331640214
Epoch: 19001Error: 0.08712847360662013


Here, We developed a neuralnetwork consisting of one hidden layer and the output layer consists of one neuron.
The activation function used here is sigmoid activation function.The neural network is trained for 20000 epochs were we obtained a constant
error

In [80]:
def calculate_output(instance):
  hidden_layer = sigmoid(np.dot(instance, weights0))
  output_layer = sigmoid(np.dot(hidden_layer, weights1))
  return output_layer[0]

In [72]:
input[0]

array([0.9231759 , 0.95743135, 0.58883739])

In [73]:
output

c#default
0             0
1             0
2             0
3             0
4             1
...         ...
1995          0
1996          0
1997          1
1998          0
1999          0

[2000 rows x 1 columns]

In [74]:
round(calculate_output(input[0]))

0

In [81]:
input[4]

array([0.93911717, 0.61005687, 0.63704537])

In [82]:
round(calculate_output(input[4]))

1